title: Lil Tang
email: tanghaohan@buaa.edu.cn
description: >-
  北京航空航天大学软件学院 · 科研实习生 · 数据挖掘 & 大模型
baseurl: ""
url: "https://ironbox-lil.github.io"
github_username: ironbox-lil
twitter_username: ""

# Author info
author:
  name: 唐皓涵
  email: tanghaohan@buaa.edu.cn
  phone: 17783691761
  location: 北京海淀

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - "*.docx"
